// This file contains bank data for the transfer page
// Format: { id: number, name: string, type: string, swift: string }
// Types: HO = Head Office, BR = Branch, SU = Subsidiary, NB = Non-Bank

// Define the Bank interface
export interface Bank {
  id: number;
  name: string;
  type: string;
  swift?: string; // Using string to store SWIFT or 'N' as per original list structure
}

/**
 * BANK DATA FORMAT EXAMPLE:
 *
 * To add more banks, follow this format:
 *
 * { id: 1, name: "BANK NAME", type: "TYPE", swift: "SWIFT_CODE" }
 *
 * Where:
 * - id: A unique number (use the number from your bank list - corresponds to the FIRST occurrence)
 * - name: The full name of the bank in UPPERCASE
 * - type: One of "HO" (Head Office), "BR" (Branch), "SU" (Subsidiary), or "NB" (Non-Bank)
 * - swift: The SWIFT/BIC code if available, or "N" if not available
 *
 * Example from your bank list:
 * Line: 58 Trusted OF AMERICA NATIONAL ASSOCIATION HO BOFAUS65
 *
 * Would be formatted as:
 * { id: 58, name: "BANK OF AMERICA NATIONAL ASSOCIATION", type: "HO", swift: "BOFAUS65" }
 */

// Bank data derived from the provided list, ensuring each unique bank name appears only once.
// The first occurrence (lowest ID) of a unique name is kept.
const bankData: Bank[] = [
  { id: 1, name: "ABBEY NAT TREASURY SVC CT BR", type: "BR", swift: "ANTSUS31XXX" },
  { id: 2, name: "ABBEY NATIONAL SECURITIES INC", type: "NB", swift: "ANSSUS33XXX" },
  { id: 3, name: "ABN AMRO BK NV NY FIFTH AVE BR", type: "BR", swift: "N" },
  { id: 4, name: "ABN AMRO INCORPORATED", type: "NB", swift: "N" },
  { id: 5, name: "ABN-AMRO BK NV CHICAGO BR", type: "BR", swift: "ABNAUS4CXXX" },
  { id: 6, name: "ABN-AMRO BK NV NY BR", type: "BR", swift: "ABNAUS33XXX" },
  { id: 7, name: "ALLIANZ GLOBAL INVESTORS DISTRIBUTORS LLC", type: "NB", swift: "N" },
  { id: 8, name: "ALLIANZ LIFE FINANCIAL SERVICES LLC", type: "NB", swift: "N" },
  { id: 9, name: "ALLIED IRISH BANKS NORTH AMERICA INC", type: "NB", swift: "N" },
  { id: 10, name: "ALLIED IRISH BKS NY BR", type: "BR", swift: "N" },
  { id: 11, name: "AMEGY BANK NATIONAL ASSOCIATION", type: "HO", swift: "SWBKUS44" },
  { id: 12, name: "AMEGY INVESTMENTS INC", type: "NB", swift: "N" },
  { id: 13, name: "AMERICAN EXPRESS CENTURION BANK", type: "HO", swift: "N" },
  { id: 14, name: "AMERICAN EXPRESS COMPANY", type: "HO", swift: "N" },
  { id: 15, name: "AMERIKA SAMOA BANK", type: "SU", swift: "ANZBASPAXXX" },
  { id: 16, name: "ANZ GUAM INC", type: "SU", swift: "N" },
  { id: 17, name: "ANZ SECURITIES INC", type: "NB", swift: "N" },
  { id: 18, name: "ARAB BKG CORP NY BR", type: "BR", swift: "ABCOUS33XXX" },
  { id: 19, name: "ASSET BACKED SECURITIES CORPORATION", type: "NB", swift: "N" },
  { id: 20, name: "AUSTRALIA & NEW ZEALAND NY BR", type: "BR", swift: "ANZBUS33XXX" },
  { id: 21, name: "AUTOMATED TRADING DESK BROKERAGE SERVICES LLC", type: "NB", swift: "N" },
  { id: 22, name: "AUTOMATED TRADING DESK FINANCIAL SERVICES LLC", type: "NB", swift: "N" },
  { id: 23, name: "BANC OF AMERICA FINANCIAL PRODUCTS INC", type: "NB", swift: "N" },
  { id: 24, name: "BANC OF AMERICA SECURITIES LLC", type: "NB", swift: "N" },
  { id: 25, name: "BANCA IMI SECURITIES CORP", type: "NB", swift: "N" },
  { id: 26, name: "BANCA MONTE DEI PASCHI NY BR", type: "BR", swift: "N" },
  { id: 27, name: "BANCAFE INTERNATIONAL B*B", type: "SU", swift: "N" },
  { id: 28, name: "BANCO BILBAO VIZCAYA ARG NY BR", type: "BR", swift: "BBVAUS33XXX" },
  { id: 29, name: "BANCO BILBAO VIZCAYA ARGENTARIA PUERTO RICO", type: "SU", swift: "N" },
  { id: 30, name: "BANCO BRADESCO SA NY BR", type: "BR", swift: "BBDEUS33XXX" },
  { id: 31, name: "BANCO DE CREDITO E INV MIA BR", type: "BR", swift: "CREDUS3MXXX" },
  { id: 32, name: "BANCO DE SABADELL SA MIAMI BR", type: "BR", swift: "BSABUS3XXXX" },
  { id: 33, name: "BANCO DEL ESTADO D CHILE NY BR", type: "BR", swift: "N" },
  { id: 34, name: "BANCO DO BRASIL SA NY BR", type: "BR", swift: "BRASUS33XXX" },
  { id: 35, name: "BANCO DO ESTADO RIO GRAN NY BR", type: "BR", swift: "N" },
  { id: 36, name: "BANCO ESPANOL CREDITO NY BR", type: "BR", swift: "ESPCUS3NXXX" },
  { id: 37, name: "BANCO ESPIRITO SANTO CMR NY BR", type: "BR", swift: "BESCUS33XXX" },
  { id: 38, name: "BANCO ESPIRITO SANTO NY BR", type: "BR", swift: "N" },
  { id: 39, name: "BANCO ITAU EUROPA INTERNATIONAL", type: "SU", swift: "ITAUUSM1XXX" },
  { id: 40, name: "BANCO ITAU SA NY BR", type: "BR", swift: "ITAUUS33XXX" },
  { id: 41, name: "BANCO LATINOAMERICANO NY AGY", type: "BR", swift: "N" },
  { id: 42, name: "BANCO POPULAR DE PUERTO RICO", type: "HO", swift: "BPPRPRSX" },
  { id: 43, name: "BANCO SANTANDER INTERNATIONAL", type: "SU", swift: "N" },
  { id: 44, name: "BANCO SANTANDER PUERTO RICO", type: "SU", swift: "N" },
  { id: 45, name: "BANCO SANTANDER SA NY BR", type: "BR", swift: "BSCHUS33XXX" },
  { id: 46, name: "BANCORPSOUTH BANK", type: "HO", swift: "N" },
  { id: 47, name: "BANCORPSOUTH INC", type: "HO", swift: "N" },
  { id: 48, name: "BANCORPSOUTH INVESTMENT SERVICES INC", type: "NB", swift: "N" },
  { id: 49, name: "BANCWEST CORPORATION", type: "SU", swift: "N" },
  { id: 50, name: "BANCWEST INVESTMENT SERVICES INC", type: "NB", swift: "N" },
  { id: 51, name: "BANK EAST ASIA LIMITED NY WHOLESALE BR", type: "BR", swift: "N" },
  { id: 52, name: "BANK LEUMI LE-ISRAEL CORPORATION", type: "HO", swift: "N" },
  { id: 53, name: "BANK LEUMI USA", type: "HO", swift: "LUMIUS3N" },
  { id: 54, name: "BANK NOVA SCOTIA PORTLAND BR", type: "BR", swift: "NOSCUS33XXX" },
  { id: 55, name: "BANK NOVA SCOTIA ST THOMAS BR", type: "BR", swift: "N" },
  { id: 56, name: "BANK NOVA SCOTIA SUNNY ISLE BR", type: "BR", swift: "N" },
  { id: 57, name: "BANK OF AMERICA CORPORATION", type: "HO", swift: "N" },
  { id: 58, name: "BANK OF AMERICA NATIONAL ASSOCIATION", type: "HO", swift: "BOFAUS65" },
  { id: 59, name: "BANK OF BARODA NY BR", type: "BR", swift: "BARBUS33XXX" },
  { id: 60, name: "BANK OF EAST ASIA (U.SA) NATIONAL ASSOCIATION THE", type: "SU", swift: "BEAKUS33XXX" },
  { id: 61, name: "BANK OF EAST ASIA LIMITED LA BR", type: "BR", swift: "BEASUS66XXX" },
  { id: 62, name: "BANK OF EAST ASIA LIMITED NY BR", type: "BR", swift: "BEASUS33XXX" },
  { id: 63, name: "BANK OF HAWAII", type: "HO", swift: "BOHIUS77" },
  { id: 64, name: "BANK OF HAWAII CORPORATION", type: "HO", swift: "N" },
  { id: 65, name: "BANK OF INDIA NY BR", type: "BR", swift: "SKIDUD33XXX" },
  { id: 66, name: "BANK OF INDIA SF AGY", type: "BR", swift: "BKIDUS33XXX" },
  { id: 67, name: "BANK OF MONTREAL CHICAGO BR", type: "BR", swift: "N" },
  { id: 68, name: "BANK OF MONTREAL NY BR", type: "BR", swift: "N" },
  { id: 69, name: "BANK OF MONTREAL-HOUSTON AGY", type: "BR", swift: "BOFMUS4XXXX" },
  { id: 70, name: "BANK OF NEW YORK MELLON CORPORATION THE", type: "HO", swift: "N" },
  { id: 71, name: "BANK OF NEW YORK MELLON THE", type: "HO", swift: "IRVTUS3N" },
  { id: 72, name: "BANK OF NOVA SCOT SAN JUAN BR", type: "BR", swift: "N" },
  { id: 73, name: "BANK OF NOVA SCOTIA HOU BR", type: "BR", swift: "N" },
  { id: 74, name: "BANK OF NOVA SCOTIA NY AGY", type: "BR", swift: "NOSCUS33XXX" },
  { id: 75, name: "BANK OF OKLAHOMA NATIONAL ASSOCIATION", type: "HO", swift: "BAOKUS44" },
  { id: 76, name: "BANK OF TAIWAN LA BR", type: "BR", swift: "BKTWUS6L" },
  { id: 77, name: "BANK OF TAIWAN NY AGY", type: "BR", swift: "BKTWUS33XXX" },
  { id: 78, name: "BANK OF THE ORIENT", type: "HO", swift: "BOFOUS6L" },
  { id: 79, name: "BANK OF THE WEST", type: "SU", swift: "BWSTUS66" },
  { id: 80, name: "BANK OF TOKYO-MITSUBISHI UFJ TRUST COMPANY", type: "SU", swift: "BOTKUS3NXXX" },
  { id: 81, name: "BANK SINOPAC LA BR", type: "BR", swift: "SINOUS6LXXX" },
  { id: 82, name: "BANK TOK-MIT UFJ ATL AGY", type: "BR", swift: "N" },
  { id: 83, name: "BANK TOK-MIT UFJ CHICAGO BR", type: "BR", swift: "BOTKUS4C" },
  { id: 84, name: "BANK TOK-MIT UFJ HOU AGY", type: "BR", swift: "BOTKUS4H" },
  { id: 85, name: "BANK TOK-MIT UFJ LA BR", type: "BR", swift: "BOTKUS6LXXX" },
  { id: 86, name: "BANK TOK-MIT UFJ NY BR", type: "BR", swift: "BOTKUS33XXX" },
  { id: 87, name: "BANK TOK-MIT UFJ PORTLAND BR", type: "BR", swift: "N" },
  { id: 88, name: "BANK TOK-MIT UFJ SEATTLE BR", type: "BR", swift: "BOTKUS6P" },
  { id: 89, name: "BANK TOK-MIT UFJ SF BR", type: "BR", swift: "BOTKUS6SXXX" },
  { id: 90, name: "BANKERS INTERNATIONAL CORPORATION", type: "SU", swift: "N" },
  { id: 91, name: "BANKOH INVESTMENT SERVICES INC", type: "NB", swift: "N" },
  { id: 92, name: "BANORTE USA CORPORATION", type: "SU", swift: "N" },
  { id: 93, name: "BARCLAYS BANK DELAWARE", type: "SU", swift: "N" },
  { id: 94, name: "BARCLAYS BK PLC LA AGY", type: "BR", swift: "N" },
  { id: 95, name: "BARCLAYS BK PLC MIAMI BR", type: "BR", swift: "BARCUS3MXXX" },
  { id: 96, name: "BARCLAYS BK PLC NY PARK AVE BR", type: "BR", swift: "BARCUS33XXX" },
  { id: 97, name: "BARCLAYS BK PLC NY SEVENTH AVE BR", type: "BR", swift: "N" },
  { id: 98, name: "BARCLAYS CAPITAL INC", type: "NB", swift: "BARCUS3BXXX" },
  { id: 99, name: "BARCLAYS FINANCIAL CORP", type: "SU", swift: "N" },
  { id: 100, name: "BARCLAYS GLOBAL INVESTORS SERVICES", type: "NB", swift: "N" },
  { id: 101, name: "BARCLAYS GROUP US INC", type: "SU", swift: "N" },
  { id: 102, name: "BAYERISCHE HYPO VEREINS NY BR", type: "BR", swift: "HYVEUS33XXX" },
  { id: 103, name: "BAYERISCHE LANDESBANK NY BR", type: "BR", swift: "BYLAUS33XXX" },
  { id: 104, name: "BB&T AM DISTRIBUTORS INC", type: "NB", swift: "N" },
  { id: 105, name: "BB&T CORPORATION", type: "HO", swift: "N" },
  { id: 106, name: "BB&T INVESTMENT SERVICES INC", type: "NB", swift: "N" },
  { id: 107, name: "BBVA BANCOMER SA HOUSTON AGY", type: "BR", swift: "N" },
  { id: 108, name: "BBVA COMPASS INVESTMENT SOLUTIONS INC", type: "NB", swift: "N" },
  { id: 109, name: "BBVA PR HOLDING CORPORATION", type: "SU", swift: "N" },
  { id: 110, name: "BBVA SECURITIES INC", type: "NB", swift: "BBVAUS3SXXX" },
  { id: 111, name: "BBVA USA BANCSHARES INC", type: "SU", swift: "N" },
  { id: 112, name: "BCP HOLDINGS (USA) INC", type: "SU", swift: "N" },
  { id: 113, name: "BLACKROCK CAPITAL MARKETS LLC", type: "NB", swift: "N" },
  { id: 114, name: "BMO CAPITAL MARKETS CORP", type: "NB", swift: "N" },
  { id: 115, name: "BMO CAPITAL MARKETS GKST INC", type: "NB", swift: "N" },
  { id: 116, name: "BMO HOLDING FINANCE LLC", type: "NB", swift: "N" },
  { id: 117, name: "BNP PARIBAS CHICAGO BR", type: "BR", swift: "BNPAUS6SXXX" },
  { id: 118, name: "BNP PARIBAS EQUITABLE TOWER BR", type: "BR", swift: "N" },
  { id: 119, name: "BNP PARIBAS HOUSTON AGY", type: "BR", swift: "BNPAUS4HXXX" },
  { id: 120, name: "BNP PARIBAS INVESTMENT SERVICES LLC", type: "NB", swift: "N" },
  { id: 121, name: "BNP PARIBAS PRIME BROKERAGE INC", type: "NB", swift: "BNPAUS3NPBS" },
  { id: 122, name: "BNP PARIBAS SECURITIES CORP", type: "NB", swift: "BNPAUS3CXXX" },
  { id: 123, name: "BNP PARIBAS SF BR", type: "BR", swift: "BNPAUS6SXXX" },
  { id: 124, name: "BNY CONVERGEX EXECUTION SOLUTIONS LLC", type: "NB", swift: "CVGXUS33XXX" },
  { id: 125, name: "BNY MELLON CAPITAL MARKETS LLC", type: "NB", swift: "N" },
  { id: 126, name: "BNY MELLON SECURITIES LLC", type: "NB", swift: "N" },
  { id: 127, name: "BNY MELLON TRUST OF DELAWARE", type: "HO", swift: "N" },
  { id: 128, name: "BOK FINANCIAL CORPORATION", type: "HO", swift: "N" },
  { id: 129, name: "BRADESCO SECURITIES INC", type: "NB", swift: "N" },
  { id: 130, name: "BRANCH BANKING AND TRUST COMPANY", type: "HO", swift: "N" },
  { id: 131, name: "BRIDGEFORD GROUP INC THE", type: "NB", swift: "N" },
  { id: 132, name: "BTMU FINANCIAL SERVICES INC", type: "NB", swift: "N" },
  { id: 133, name: "BTMU NORTH AMERICA INTERNATIONAL INC", type: "SU", swift: "N" },
  { id: 134, name: "CAIXA DE AFORROS MIAMI BR", type: "BR", swift: "CAVIUS3MXXX" },
  { id: 135, name: "CAIXA GERAL DE DEPOSITOS NY BR", type: "BR", swift: "CGDIUS33XXX" },
  { id: 136, name: "CAJA DE AHORROS DE VAL MIA BR", type: "BR", swift: "CAGLUS3MXXX" },
  { id: 137, name: "CALIFORNIA BANK & TRUST", type: "HO", swift: "N" },
  { id: 138, name: "CALYON CHICAGO BR", type: "BR", swift: "CRLYUS33XXX" },
  { id: 139, name: "CALYON NY BR", type: "BR", swift: "CRLSUS33XXX" },
  { id: 140, name: "CALYON SECURITIES (USA) INC", type: "NB", swift: "CRLSUS33XXX" },
  { id: 141, name: "CANADIAN IMPERIAL BK CHGO BR", type: "BR", swift: "CIBCUS3104C" },
  { id: 142, name: "CANTOR FITZGERALD & CO", type: "HO", swift: "N" },
  { id: 143, name: "CAPITAL ONE BANK (USA) NATIONAL ASSOCIATION", type: "HO", swift: "N" },
  { id: 144, name: "CAPITAL ONE FINANCIAL CORPORATION", type: "HO", swift: "N" },
  { id: 145, name: "CAPITAL ONE INVESTMENT SERVICES LLC", type: "NB", swift: "N" },
  { id: 146, name: "CAPITAL ONE NATIONAL ASSOCIATION", type: "HO", swift: "HIBKUS44" },
  { id: 147, name: "CAPITAL ONE SECURITIES LLC", type: "NB", swift: "N" },
  { id: 148, name: "CAROLINA FIRST BANK", type: "HO", swift: "CFBKUS33" },
  { id: 149, name: "CATHAY BANK", type: "HO", swift: "CATHUS6LXXX" },
  { id: 150, name: "CATHAY GENERAL BANCORP", type: "HO", swift: "N" },
  { id: 151, name: "CATHAY UNITED BK LA AGY", type: "BR", swift: "UWCBUS6LXXX" },
  { id: 152, name: "CCBDE INC", type: "NB", swift: "N" },
  { id: 153, name: "CHANG HWA CMRL BK LA BR", type: "BR", swift: "CCBCUS33XXX" },
  { id: 154, name: "CHANG HWA CMRL BK NY BR", type: "BR", swift: "CCBCUS33XXX" },
  { id: 155, name: "CHARTER ONE SECURITIES INC", type: "NB", swift: "N" },
  { id: 156, name: "CHASE BANK USA NATIONAL ASSOCIATION", type: "HO", swift: "N" },
  { id: 157, name: "CHEVY CHASE SECURITIES INC", type: "NB", swift: "N" },
  { id: 158, name: "CHIBA BK NY BR", type: "BR", swift: "CHBAUS31XXX" },
  { id: 159, name: "CHINATRUST BANK (U.SA)", type: "SU", swift: "CTHCUS66" },
  { id: 160, name: "CHINATRUST CAPITAL CORPORATION", type: "SU", swift: "N" },
  { id: 161, name: "CHINATRUST COMMERCIAL BK NY BR", type: "BR", swift: "CTCBUS33XXX" },
  { id: 162, name: "CHONG HING BANK LIMITED SF BR", type: "BR", swift: "LCHBUS61XXX" },
  { id: 163, name: "CIBC WORLD MARKETS CORP", type: "NB", swift: "OPCOUS33XXX" },
  { id: 164, name: "CITI INTERNATIONAL FINANCIAL SERVICES LLC", type: "NB", swift: "N" },
  { id: 165, name: "CITIBANK NA", type: "HO", swift: "CITIUS33" },
  { id: 166, name: "CITIC KA WAH BK LA BR", type: "BR", swift: "KWHKUS66XXX" },
  { id: 167, name: "CITIC KA WAH BK NY BR", type: "BR", swift: "KWHKUS33XXX" },
  { id: 168, name: "CITICORP MORTGAGE SECURITIES INC", type: "NB", swift: "N" },
  { id: 169, name: "CITICORP SECURITIES SERVICES INC", type: "NB", swift: "N" },
  { id: 170, name: "CITIFINANCIAL MORTGAGE SECURITIES INC", type: "NB", swift: "N" },
  { id: 171, name: "CITIGROUP GLOBAL MARKETS INC", type: "NB", swift: "SBSIUS33XXX" },
  { id: 172, name: "CITIGROUP GLOBAL MARKETS PUERTO RICO INC", type: "NB", swift: "N" },
  { id: 173, name: "CITIGROUP GLOBAL MARKETS VEHICLE SECURITIES INC", type: "NB", swift: "N" },
  { id: 174, name: "CITIGROUP INC", type: "HO", swift: "N" },
  { id: 175, name: "CITIGROUP VEHICLE SECURITIES INC", type: "NB", swift: "N" },
  { id: 176, name: "CITIZENS BANCORP", type: "HO", swift: "N" },
  { id: 177, name: "CITIZENS BANK OF PENNSYLVANIA", type: "SU", swift: "N" },
  { id: 178, name: "CITIZENS FINANCIAL GROUP INC", type: "HO", swift: "N" },
  { id: 179, name: "CITY NATIONAL BANCSHARES INC", type: "SU", swift: "N" },
  { id: 180, name: "CITY NATIONAL BANK OF FLORIDA", type: "SU", swift: "CNBFUS31XXX" },
  { id: 181, name: "CLS BANK INTERNATIONAL", type: "SU", swift: "CLSBUS33XXX" },
  { id: 182, name: "CM FLORIDA HOLDINGS INC", type: "SU", swift: "N" },
  { id: 183, name: "COBIZ BANK", type: "HO", swift: "N" },
  { id: 184, name: "COBIZ FINANCIAL INC", type: "HO", swift: "N" },
  { id: 185, name: "COLLATERALIZED MORTGAGE SECURITIES CORPORATION", type: "NB", swift: "N" },
  { id: 186, name: "COLONIAL INVESTMENT SERVICES OF FLORIDA INC", type: "NB", swift: "N" },
  { id: 187, name: "COLUMBTrusted AND TRUST COMPANY", type: "HO", swift: "COBTUS31" },
  { id: 188, name: "COMERICA BANK", type: "HO", swift: "MBBDUS33" },
  { id: 189, name: "COMERICA INCORPORATED", type: "HO", swift: "N" },
  { id: 190, name: "COMERICA SECURITIES INC", type: "NB", swift: "N" },
  { id: 191, name: "COMMERCE BANK OF WASHINGTON NATIONAL ASSOCIATION", type: "HO", swift: "N" },
  { id: 192, name: "COMMERCE CAPITAL INVESTMENTS INC", type: "NB", swift: "N" },
  { id: 193, name: "COMMERZBANK AG NY BR", type: "BR", swift: "COBAUS3XXXX" },
  { id: 194, name: "COMMERZBANK BK NY BR", type: "BR", swift: "DRESUS33XXX" },
  { id: 195, name: "COMMERZBANK CAPITAL MARKETS CORPORATION", type: "NB", swift: "N" },
  { id: 196, name: "COMMONWEALTH AUSTRALIA SECURITIES LLC", type: "NB", swift: "N" },
  { id: 197, name: "COMMONWEALTH BK OF AUS NY BR", type: "BR", swift: "CTBAUS33XXX" },
  { id: 198, name: "COMPASS BANCSHARES INC", type: "SU", swift: "N" },
  { id: 199, name: "COMPASS BANK", type: "SU", swift: "CPASUS44" },
  { id: 200, name: "CORPBANCA NY BR", type: "BR", swift: "CONBUS33XXX" },
  { id: 201, name: "CORPORATE ASSET BACKED CORPORATION", type: "NB", swift: "N" },
  { id: 202, name: "COUNTRYWIDE SECURITIES CORPORATION", type: "NB", swift: "CWSCUS61XXX" },
  { id: 203, name: "CREDICORP SECURITIES INC", type: "NB", swift: "N" },
  { id: 204, name: "CREDIT AGRICOLE CHEUVREUX NORTH AMERICA INC", type: "NB", swift: "N" },
  { id: 205, name: "CREDIT INDUS ET CMRL NY BR", type: "BR", swift: "CMCIUS33XXX" },
  { id: 206, name: "CREDIT SUISSE ASSET MANAGEMENT SECURITIES INC", type: "NB", swift: "N" },
  { id: 207, name: "CREDIT SUISSE CAPITAL LLC", type: "NB", swift: "CSFBUS3LXXX" },
  { id: 208, name: "CREDIT SUISSE FIRST BOSTON LOGISTICS FUNDING LLC", type: "NB", swift: "N" },
  { id: 209, name: "CREDIT SUISSE FIRST BOSTON MORTGAGE ACCEPTANCE CORP", type: "NB", swift: "N" },
  { id: 210, name: "CREDIT SUISSE MANAGEMENT LLC", type: "NB", swift: "N" },
  { id: 211, name: "CREDIT SUISSE NY BR", type: "BR", swift: "CRESUS33XXX" },
  { id: 212, name: "CREDIT SUISSE SECURITIES (USA) LLC", type: "NB", swift: "CSFBUS33XXX" },
  { id: 213, name: "CSFB INTERNATIONAL TRADING LLC", type: "NB", swift: "N" },
  { id: 214, name: "CULLEN/FROST BANKERS INC", type: "HO", swift: "N" },
  { id: 215, name: "DAEWOO SECURITIES (AMERICA) INC", type: "NB", swift: "DAESUS31XXX" },
  { id: 216, name: "DAIWA SECURITIES AMERICA INC", type: "NB", swift: "DSANUS3NXXX" },
  { id: 217, name: "DBS BK LA AGY", type: "BR", swift: "DBSSUS6LXXX" },
  { id: 218, name: "DBS VICKERS SECURITIES (USA) INC", type: "NB", swift: "N" },
  { id: 219, name: "DEAM INVESTOR SERVICES INC", type: "NB", swift: "N" },
  { id: 220, name: "DELAWARE SECURITIES PROCESSING CORP", type: "NB", swift: "N" },
  { id: 221, name: "DEPFA BK PLC NY BR", type: "BR", swift: "DPFAUS33XXX" },
  { id: 222, name: "DESJARDINS BANK NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 223, name: "DESJARDINS FSB HOLDINGS INC", type: "SU", swift: "N" },
  { id: 224, name: "DESJARDINS HALLANDALE BR", type: "BR", swift: "N" },
  { id: 225, name: "DEUTSCHE BANK FINANCIAL INC", type: "NB", swift: "N" },
  { id: 226, name: "DEUTSCHE BANK SECURITIES INC", type: "NB", swift: "NWSCUS33XXX" },
  { id: 227, name: "DEUTSCHE BANK TRUST COMPANY AMERICAS", type: "SU", swift: "BKTRUS33" },
  { id: 228, name: "DEUTSCHE BANK TRUST COMPANY DELAWARE", type: "SU", swift: "N" },
  { id: 229, name: "DEUTSCHE BANK TRUST CORPORATION", type: "SU", swift: "N" },
  { id: 230, name: "DEUTSCHE BK AG NY BR", type: "BR", swift: "DEUTUS33XXX" },
  { id: 231, name: "DEXIA CREDIT LOCAL NY BR", type: "BR", swift: "DXIAUS33XXX" },
  { id: 232, name: "DISCOUNT BANCORP INC", type: "SU", swift: "N" },
  { id: 233, name: "DNB NOR BK ASA NY BR", type: "BR", swift: "DNBAUS33XXX" },
  { id: 234, name: "DNB NOR MARKETS INC", type: "NB", swift: "N" },
  { id: 235, name: "DRESDNER KLEINWORT SECURITIES LLC", type: "NB", swift: "DSECUS33XXX" },
  { id: 236, name: "DWS INVESTMENTS DISTRIBUTORS INC", type: "NB", swift: "N" },
  { id: 237, name: "DZ BK AG DEUTSCHE ZENTRA NY BR", type: "BR", swift: "GENOUS33XXX" },
  { id: 238, name: "DZ FINANCIAL MARKETS LLC", type: "NB", swift: "N" },
  { id: 239, name: "E SUN CMRL BK LA BR", type: "BR", swift: "FSUNUS6L" },
  { id: 240, name: "E.S. FINANCIAL SERVICES INC", type: "NB", swift: "N" },
  { id: 241, name: "EAST ASIA HOLDING COMPANY INC", type: "SU", swift: "N" },
  { id: 242, name: "EAST WEST BANCORP INC", type: "HO", swift: "N" },
  { id: 243, name: "EAST WEST BANK", type: "HO", swift: "N" },
  { id: 244, name: "ERSTE GROUP BK NY BR", type: "BR", swift: "GIBAUS33XXX" },
  { id: 245, name: "ESN NORTH AMERICA INC", type: "NB", swift: "ESNAUS31XXX" },
  { id: 246, name: "ESPIRITO SANTO BANK", type: "SU", swift: "ESBFUS3MXXX" },
  { id: 247, name: "EUROHYPO AG NY BR", type: "BR", swift: "EHYPUS31XXX" },
  { id: 248, name: "EVERGREEN INVESTMENT SERVICES INC", type: "NB", swift: "N" },
  { id: 249, name: "EVERTRUST BANK", type: "SU", swift: "ETBKUS61XXX" },
  { id: 250, name: "EXANE INC", type: "NB", swift: "EXAIUS31XXX" },
  { id: 251, name: "FAIRHOLME DISTRIBUTION INC", type: "NB", swift: "N" },
  { id: 252, name: "FALCON BANCSHARES INCORPORATED", type: "HO", swift: "N" },
  { id: 253, name: "FALCON INTERNATIONAL BANK", type: "HO", swift: "N" },
  { id: 254, name: "FAR EAST NATIONAL BANK", type: "SU", swift: "FENBUS6L" },
  { id: 255, name: "FIDUCIARY TRUST COMPANY INTERNATIONAL", type: "HO", swift: "FCNYUS33XXX" },
  { id: 256, name: "FIFTH THIRD ASSET MANAGEMENT INC", type: "NB", swift: "FTSMUS31XXX" },
  { id: 257, name: "FIFTH THIRD BANCORP", type: "HO", swift: "N" },
  { id: 258, name: "FIFTH THIRD BANK", type: "HO", swift: "FTBCUS3C" },
  { id: 259, name: "FIFTH THIRD SECURITIES INC", type: "NB", swift: "N" },
  { id: 260, name: "FIRST BANCORP", type: "HO", swift: "N" },
  { id: 261, name: "FIRST CLEARING LLC", type: "NB", swift: "FCCOUS31XXX" },
  { id: 262, name: "FIRST CMRL BK GUAM BR", type: "BR", swift: "N" },
  { id: 263, name: "FIRST CMRL BK LA BR", type: "BR", swift: "FCBKUS33XXX" },
  { id: 264, name: "FIRST CMRL BK NY AGY", type: "BR", swift: "FCBKUS33XXX" },
  { id: 265, name: "FIRST COMMERCIAL BANK", type: "HO", swift: "FICOUS44" },
  { id: 266, name: "FIRST COMMERCIAL BANK (U.S.A)", type: "SU", swift: "FCBKUS33XXX" },
  { id: 267, name: "FIRST HAWAIIAN BANK", type: "SU", swift: "BOHIUS77" },
  { id: 268, name: "FIRST REPUBLIC SECURITIES COMPANY LLC", type: "NB", swift: "N" },
  { id: 269, name: "FIRST SOUTHWEST COMPANY", type: "NB", swift: "N" },
  { id: 270, name: "FIRSTBANK PUERTO RICO", type: "HO", swift: "N" },
  { id: 271, name: "FMLS INC", type: "NB", swift: "N" },
  { id: 272, name: "FORTIS BK SA/NV NY BR", type: "BR", swift: "N" },
  { id: 273, name: "FORTIS SECURITIES LLC", type: "NB", swift: "N" },
  { id: 274, name: "FRANKLIN RESOURCES INC", type: "HO", swift: "N" },
  { id: 275, name: "FROST BROKERAGE SERVICES INC", type: "NB", swift: "N" },
  { id: 276, name: "FROST NATIONAL BANK THE", type: "HO", swift: "FRSTUS44XXX" },
  { id: 277, name: "FROST SECURITIES INC", type: "NB", swift: "N" },
  { id: 278, name: "FUBON SECURITIES USA LLC", type: "NB", swift: "N" },
  { id: 279, name: "GOLDMAN SACHS & CO", type: "HO", swift: "N" },
  { id: 280, name: "GOLDMAN SACHS EXECUTION AND CLEARING L.P.", type: "NB", swift: "N" },
  { id: 281, name: "GOLDMAN SACHS GROUP INC THE", type: "HO", swift: "GSGIUS31XXX" },
  { id: 282, name: "GOOD MORNING SHINHAN SECURITIES USA INC", type: "NB", swift: "N" },
  { id: 283, name: "GOODBODY SECURITIES INC", type: "NB", swift: "N" },
  { id: 284, name: "GOVERNOR&CO BK IR STAMFORD BR", type: "BR", swift: "BOFIUS33XXX" },
  { id: 285, name: "GPC SECURITIES INC", type: "NB", swift: "N" },
  { id: 286, name: "GREAT WESTERN BANCORPORATION INC", type: "SU", swift: "N" },
  { id: 287, name: "GREAT WESTERN BANK", type: "SU", swift: "N" },
  { id: 288, name: "GREENWICH CAPITAL DERIVATIVES INC", type: "NB", swift: "N" },
  { id: 289, name: "GULF INTL BK NY BR", type: "BR", swift: "N" },
  { id: 290, name: "GULF INTL BK UK NY BR", type: "BR", swift: "N" },
  { id: 291, name: "GUNMA BANK NY BR", type: "BR", swift: "N" },
  { id: 292, name: "H.D. VEST INVESTMENT SECURITIES INC", type: "NB", swift: "N" },
  { id: 293, name: "HANDELSBANKEN MARKETS SECURITIES INC", type: "NB", swift: "N" },
  { id: 294, name: "HARRIS BANK NATIONAL ASSOCIATION THE", type: "SU", swift: "N" },
  { id: 295, name: "HARRIS BANKCORP INC", type: "SU", swift: "N" },
  { id: 296, name: "HARRIS CENTRAL NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 297, name: "HARRIS FINANCIAL CORP", type: "SU", swift: "N" },
  { id: 298, name: "HARRIS INVESTOR SERVICES INC", type: "NB", swift: "N" },
  { id: 299, name: "HARRIS NATIONAL ASSOCIATION", type: "SU", swift: "HATRUS44" },
  { id: 300, name: "HIGHMARK FUNDS DISTRIBUTORS INC", type: "NB", swift: "N" },
  { id: 301, name: "HSBC BANK NEVADA NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 302, name: "HSBC BANK USA NATIONAL ASSOCIATION", type: "SU", swift: "HSBCUS33" },
  { id: 303, name: "HSBC INTERNATIONAL FINANCE CORPORATION (DELAWARE)", type: "SU", swift: "HSDEUS33XXX" },
  { id: 304, name: "HSBC INVESTMENTS (NORTH AMERICA) INC", type: "SU", swift: "N" },
  { id: 305, name: "HSBC NORTH AMERICA HOLDINGS INC", type: "SU", swift: "N" },
  { id: 306, name: "HSBC NORTH AMERICA INC", type: "SU", swift: "N" },
  { id: 307, name: "HSBC PRIVATE BANK INTERNATIONAL", type: "SU", swift: "HSBCUS3MXXX" },
  { id: 308, name: "HSBC SECURITIES (USA) INC", type: "NB", swift: "JCSIUS33XXX" },
  { id: 309, name: "HSBC TRUST COMPANY (DELAWARE) NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 310, name: "HSBC USA INC", type: "SU", swift: "N" },
  { id: 311, name: "HSH NORDBK AG NY BR", type: "BR", swift: "HSHNUS33XXX" },
  { id: 312, name: "HUA NAN CMRL BK LA BR", type: "BR", swift: "HNBKUS6LXXX" },
  { id: 313, name: "HUA NAN CMRL BK NY AGY", type: "BR", swift: "HNBKUS6LXXX" }, // Note: Same SWIFT listed for LA and NY, kept first ID (312) for the name "HUA NAN CMRL BK LA BR"
  { id: 314, name: "HUNTINGTON BANCSHARES INCORPORATED", type: "HO", swift: "N" },
  { id: 315, name: "HUNTINGTON NATIONAL BANK THE", type: "HO", swift: "HUNTUS33" },
  { id: 316, name: "IBT HOLDINGS CORP", type: "SU", swift: "N" },
  { id: 317, name: "ICICI BK LIMITED NY BR", type: "BR", swift: "ICICUS3N" },
  { id: 318, name: "ICICI SECURITIES INC", type: "NB", swift: "N" },
  { id: 319, name: "IDB CAPITAL CORP", type: "NB", swift: "N" },
  { id: 320, name: "IMI CAPITAL MARKETS USA CORPOPRATION", type: "NB", swift: "N" }, // Typo "CORPOPRATION" kept as is from original list
  { id: 321, name: "INB FINANCIAL CORPORATION", type: "SU", swift: "N" },
  { id: 322, name: "INDUSTRIAL BK OF KOREA NY BR", type: "BR", swift: "IBKOUS33XXX" },
  { id: 323, name: "INTER NATIONAL BANK", type: "SU", swift: "ITNBUS44XXX" },
  { id: 324, name: "INTESA SANPAOLO SPA NY BR", type: "BR", swift: "IBSPUS33XXX" },
  { id: 325, name: "ISRAEL DISCOUNT BANK OF NEW YORK", type: "SU", swift: "IDBYUS33" },
  { id: 326, name: "ITAU SECURITIES INC", type: "NB", swift: "N" },
  { id: 327, name: "IXE SECURITIES LLC", type: "NB", swift: "N" },
  { id: 328, name: "J.P. MORGAN ALTERNATIVE ASSET MANAGEMENT INC", type: "NB", swift: "N" },
  { id: 329, name: "J.P. MORGAN CLEARING CORP", type: "NB", swift: "N" },
  { id: 330, name: "J.P. MORGAN SECURITIES INC", type: "NB", swift: "N" },
  { id: 331, name: "J.P. MORGAN WHITEFRIARS INC", type: "NB", swift: "N" },
  { id: 332, name: "JEFFERIES & COMPANY INC", type: "HO", swift: "JEFFUS33XXX" },
  { id: 333, name: "JOHNSON BANK", type: "HO", swift: "JNBKUS44" },
  { id: 334, name: "JOHNSON FINANCIAL GROUP INC", type: "HO", swift: "N" },
  { id: 335, name: "JPMORGAN CHASE & CO", type: "HO", swift: "N" },
  { id: 336, name: "JPMORGAN CHASE BANK NATIONAL ASSOCIATION", type: "HO", swift: "CHASUS33" },
  { id: 337, name: "KBC BANK NV NY BR", type: "BR", swift: "N" },
  { id: 338, name: "KBC NORTH AMERICA FINANCE CORPORATION", type: "NB", swift: "N" },
  { id: 339, name: "KEYBANK NATIONAL ASSOCIATION", type: "HO", swift: "KEYUS33" },
  { id: 340, name: "KEYCORP", type: "HO", swift: "N" },
  { id: 341, name: "KOOKMIN BK NY BR", type: "BR", swift: "CZNBUS33XXX" },
  { id: 342, name: "KOREA DEVELOPMENT BK NY BR", type: "BR", swift: "KODBUS33XXX" },
  { id: 343, name: "LAND BK OF TAIWAN LA BR", type: "BR", swift: "LBOTUS66" },
  { id: 344, name: "LANDESBANK HESSEN-THURIN NY BR", type: "BR", swift: "N" },
  { id: 345, name: "LANDESBK BADEN WUERTTEMB NY BR", type: "BR", swift: "N" },
  { id: 346, name: "LAVAFLOW INC", type: "NB", swift: "N" },
  { id: 347, name: "LBBW SECURITIES LLC", type: "NB", swift: "N" },
  { id: 348, name: "LEUMI INVESTMENT SERVICES INC", type: "NB", swift: "N" },
  { id: 349, name: "LLOYDS TSB BK PLC NY BR", type: "BR", swift: "LOYDUS33NYB" },
  { id: 350, name: "LOCKWOOD ADVISORS INC", type: "NB", swift: "N" },
  { id: 351, name: "LOCKWOOD CAPITAL MANAGEMENT INC", type: "NB", swift: "N" },
  { id: 352, name: "M&I CUSTODY OF NEVADA INC", type: "NB", swift: "N" },
  { id: 353, name: "M&I FINANCIAL ADVISORS INC", type: "NB", swift: "N" },
  { id: 354, name: "M&I MARSHALL & ILSLEY BANK", type: "HO", swift: "MARLUS44" },
  { id: 355, name: "M&T BANK CORPORATION", type: "SU", swift: "N" },
  { id: 356, name: "M&T BANK NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 357, name: "M&T SECURITIES INC", type: "NB", swift: "N" },
  { id: 358, name: "MAEDGEN & WHITE LTD", type: "HO", swift: "N" },
  { id: 359, name: "MANUFACTURERS AND TRADERS TRUST COMPANY", type: "SU", swift: "MANTUS31" },
  { id: 360, name: "MANUFACTURERS BANK", type: "SU", swift: "MITKUS6L" },
  { id: 361, name: "MARATHON BANKING CORPORATION", type: "SU", swift: "N" },
  { id: 362, name: "MARATHON NATIONAL BANK OF NEW YORK", type: "SU", swift: "MRANUS31XXX" },
  { id: 363, name: "MARINE MIDLAND OVERSEAS CORPORATION", type: "SU", swift: "N" },
  { id: 364, name: "MARSHALL & ILSLEY CORPORATION", type: "HO", swift: "N" },
  { id: 365, name: "MBSC SECURITIES CORPORATION", type: "NB", swift: "N" },
  { id: 366, name: "MEGA INTL CMRL BK CHICAGO BR", type: "BR", swift: "ICBCUS4CXXX" },
  { id: 367, name: "MEGA INTL CMRL BK CO NY BR", type: "BR", swift: "ICBCUS33XXX" },
  { id: 368, name: "MEGA INTL CMRL BK LA BR", type: "BR", swift: "ICBCUS6LXXX" },
  { id: 369, name: "MEGA INTL CMRL SILICON VALL BR", type: "BR", swift: "ICBCUS6SXXX" },
  { id: 370, name: "MERCER ALLIED COMPANY L.P.", type: "NB", swift: "N" },
  { id: 371, name: "MERRILL LYNCH FINANCIAL MARKETS INC", type: "NB", swift: "N" },
  { id: 372, name: "MERRILL LYNCH GOVERNMENT SECURITIES INC", type: "NB", swift: "MLGSUS31XXX" },
  { id: 373, name: "MERRILL LYNCH MONEY MARKETS INC", type: "NB", swift: "N" },
  { id: 374, name: "MERRILL LYNCH PIERCE FENNER & SMITH INCORPORATED", type: "NB", swift: "N" },
  { id: 375, name: "MERRILL LYNCH PROFESSIONAL CLEARING CORP", type: "NB", swift: "MLCOUS3GPRO" },
  { id: 376, name: "MGI FUNDS DISTRIBUTORS INC", type: "NB", swift: "N" },
  { id: 377, name: "MILLENNIUM BCPBANK NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 378, name: "MITSUBISHI UFJ SECURITIES (USA) INC", type: "NB", swift: "N" },
  { id: 379, name: "MITSUBISHI UFJ TR & BKG NY BR", type: "BR", swift: "MTBCUS33XXX" },
  { id: 380, name: "MITSUBISHI UFJ TRUST & BANKING CORPORATION (U.SA)", type: "SU", swift: "MTUSUS33" },
  { id: 381, name: "MIZUHO CAPITAL MARKETS CORPORATION", type: "NB", swift: "FCMCUS33XXX" },
  { id: 382, name: "MIZUHO CORP BK CHICAGO BR", type: "BR", swift: "N" },
  { id: 383, name: "MIZUHO CORPORATE BANK (USA)", type: "SU", swift: "MHCCUS33XXX" },
  { id: 384, name: "MIZUHO CORPORATE BANK OF CALIFORNIA", type: "SU", swift: "DKBCUS66XXX" },
  { id: 385, name: "MIZUHO CORPORATE BK LA BR", type: "BR", swift: "MHCBUS6LXXX" },
  { id: 386, name: "MIZUHO CORPORATE NY BR", type: "BR", swift: "MHCBUS33XXX" },
  { id: 387, name: "MIZUHO SECURITIES USA INC", type: "NB", swift: "MHSCUS33XXX" },
  { id: 388, name: "MIZUHO TRUST & BANKING CO (USA)", type: "SU", swift: "YBTPUS33" },
  { id: 389, name: "MORGAN KEEGAN FINANCIAL PRODUCTS INC", type: "NB", swift: "N" },
  { id: 390, name: "MORGAN STANLEY", type: "SU", swift: "MSAMUS33XXX" },
  { id: 391, name: "MORGAN STANLEY & CO INCORPORATED", type: "NB", swift: "MSNYUS33XXX" },
  { id: 392, name: "MORTGAGE ASSET SECURITIZATION TRANSACTIONS INC", type: "NB", swift: "N" },
  { id: 393, name: "NABCAPITAL SECURITIES LLC", type: "NB", swift: "N" },
  { id: 394, name: "NANYANG CMRL BK SF BR", type: "BR", swift: "NYCBUS6SXXX" },
  { id: 395, name: "NATBANK NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 396, name: "NATBC HOLDING CORPORATION", type: "SU", swift: "N" },
  { id: 397, name: "NATIONAL AMERICAS HOLDINGS LLC", type: "SU", swift: "N" },
  { id: 398, name: "NATIONAL AMERICAS INVESTMENT INC", type: "SU", swift: "N" },
  { id: 399, name: "NATIONAL AUSTRALIA BK NY BR", type: "BR", swift: "NATAUS33XXX" },
  { id: 400, name: "NATIONAL AUSTRALIA FUNDING (DELAWARE) INC", type: "NB", swift: "N" },
  { id: 401, name: "NATIONAL BANK OF ARIZONA", type: "HO", swift: "N" },
  { id: 402, name: "NATIONAL BANK OF CANADA FINANCIAL INC", type: "NB", swift: "N" },
  { id: 403, name: "NATIONAL BANK OF INDIANAPOLIS CORPORATION THE", type: "HO", swift: "N" },
  { id: 404, name: "NATIONAL BANK OF INDIANAPOLIS THE", type: "HO", swift: "N" },
  { id: 405, name: "NATIONAL BK OF CANADA NY BR", type: "BR", swift: "BNDCUS33XXX" },
  { id: 406, name: "NATIXIS BLEICHROEDER INC", type: "NB", swift: "N" },
  { id: 407, name: "NATIXIS DERIVATIVES INC", type: "NB", swift: "N" },
  { id: 408, name: "NATIXIS NY AVE OF THE AMERICAS BR", type: "BR", swift: "N" },
  { id: 409, name: "NATIXIS NY BR", type: "BR", swift: "BFCEUS33XXX" },
  { id: 410, name: "NBC SECURITIES INC", type: "NB", swift: "N" },
  { id: 411, name: "NICHOLAS-APPLEGATE SECURITIES LLC", type: "NB", swift: "N" },
  { id: 412, name: "NOMURA SECURITIES INTERNATIONAL INC", type: "NB", swift: "NMRIUS33XXX" },
  { id: 413, name: "NORDDEUTSCHE LANDESBANK NY BR", type: "BR", swift: "NOLAUS33XXX" },
  { id: 414, name: "NORDEA BK FINLAND PLC NY BR", type: "BR", swift: "NDEAUS3NXXX" },
  { id: 415, name: "NORDEA BK NORGE NY BR", type: "BR", swift: "N" },
  { id: 416, name: "NORINCHUKIN BK NY BR", type: "BR", swift: "NOCUUS33XXX" },
  { id: 417, name: "NORTHERN TRUST COMPANY THE", type: "HO", swift: "CNORUS44" },
  { id: 418, name: "NORTHERN TRUST CORPORATION", type: "HO", swift: "N" },
  { id: 419, name: "NORTHERN TRUST INTERNATIONAL BANKING CORPORATION THE", type: "SU", swift: "N" },
  { id: 420, name: "OCEANIC BANK", type: "SU", swift: "N" },
  { id: 421, name: "OCEANIC HOLDING (BVI) LIMITED", type: "SU", swift: "N" },
  { id: 422, name: "ORIENT BANCORPORATION", type: "HO", swift: "N" },
  { id: 423, name: "OVERSEA-CHINESE BKG LA AGY", type: "BR", swift: "OCBCUS6LXXX" },
  { id: 424, name: "PAINEWEBBER MORTGAGE ACCEPTANCE CORPORATION III", type: "NB", swift: "N" },
  { id: 425, name: "PERSHING ADVISOR SOLUTIONS LLC", type: "NB", swift: "N" },
  { id: 426, name: "PERSHING LLC", type: "NB", swift: "PRSHUS33XXX" },
  { id: 427, name: "PETRA INTERNATIONAL BANKING CORPORATION", type: "HO", swift: "N" },
  { id: 428, name: "PFPC DISTRIBUTORS INC", type: "NB", swift: "N" },
  { id: 429, name: "PFS INVESTMENTS INC", type: "NB", swift: "N" },
  { id: 430, name: "PLAINSCAPITAL BANK", type: "HO", swift: "PLASUS41" },
  { id: 431, name: "PNC BANK NATIONAL ASSOCIATION", type: "HO", swift: "PNCCUS33" },
  { id: 432, name: "PNC FINANCIAL SERVICES GROUP INC THE", type: "HO", swift: "N" },
  { id: 433, name: "PNC INVESTMENTS LLC", type: "NB", swift: "N" },
  { id: 434, name: "POPULAR INC", type: "HO", swift: "N" },
  { id: 435, name: "PRISM FINANCIAL CORPORATION", type: "SU", swift: "N" },
  { id: 436, name: "PROCTOR INVESTMENT DISTRIBUTORS LLC", type: "NB", swift: "N" },
  { id: 437, name: "RABO SECURITIES USA INC", type: "NB", swift: "N" },
  { id: 438, name: "RABOBANK NATIONAL ASSOCIATION", type: "SU", swift: "RABOUS66XXX" },
  { id: 439, name: "RABOBANK NEDERLAND NY BR", type: "BR", swift: "RABOUS33XXX" },
  { id: 440, name: "RABOBANK NEDERLAND ST. LOUIS AGY", type: "BR", swift: "N" },
  { id: 441, name: "RBC BANCORPORATION (USA)", type: "SU", swift: "N" },
  { id: 442, name: "RBC BANK (GEORGIA) NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 443, name: "RBC BANK (USA)", type: "SU", swift: "CNTAUS33" },
  { id: 444, name: "RBC CAPITAL MARKETS CORPORATION", type: "NB", swift: "N" },
  { id: 445, name: "RBC HOLDINGS (USA) INC", type: "SU", swift: "N" },
  { id: 446, name: "RBC USA HOLDCO CORPORATION", type: "SU", swift: "N" },
  { id: 447, name: "RBS CITIZENS NATIONAL ASSOCIATION", type: "SU", swift: "CTZIUS33XXX" },
  { id: 448, name: "RBS SECURITIES CORPORATION", type: "NB", swift: "N" },
  { id: 449, name: "RBS SECURITIES INC", type: "NB", swift: "GRNWUS33XXX" },
  { id: 450, name: "RED CAPITAL MARKETS INC", type: "NB", swift: "N" },
  { id: 451, name: "REGIONS BANK", type: "HO", swift: "FABSUS44" },
  { id: 452, name: "REGIONS FINANCIAL CORPORATION", type: "HO", swift: "N" },
  { id: 453, name: "REPUBLIC NEW YORK SECURITIES CORPORATION", type: "NB", swift: "N" },
  { id: 454, name: "ROBECO INSTITUTIONAL ASSET MANAGEMENT U.S. INC", type: "NB", swift: "N" },
  { id: 455, name: "ROYAL BANK HOLDING INC", type: "SU", swift: "N" },
  { id: 456, name: "ROYAL BK CANADA NY THREE WORLD FNCL CTR BR", type: "BR", swift: "N" },
  { id: 457, name: "ROYAL BK OF CANADA DALLAS AGY", type: "BR", swift: "N" },
  { id: 458, name: "ROYAL BK OF CANADA HOU AGY", type: "BR", swift: "N" },
  { id: 459, name: "ROYAL BK OF CANADA LIB PL BR", type: "BR", swift: "N" },
  { id: 460, name: "ROYAL BK OF CANADA MIAMI BR", type: "BR", swift: "N" },
  { id: 461, name: "ROYAL BK OF CANADA NY BR", type: "BR", swift: "ROYCUS3XXXX" },
  { id: 462, name: "ROYAL BK OF CANADA PORTLAND BR", type: "BR", swift: "N" },
  { id: 463, name: "SANTANDER BANCORP", type: "SU", swift: "N" },
  { id: 464, name: "SANTANDER INVESTMENT SECURITIES INC", type: "NB", swift: "N" },
  { id: 465, name: "SANTANDER SECURITIES CORPORATION", type: "NB", swift: "N" },
  { id: 466, name: "SCOTIA CAPITAL (USA) INC", type: "NB", swift: "N" },
  { id: 467, name: "SCOTIABANK DE PUERTO RICO", type: "SU", swift: "NOSCPR22XXX" },
  { id: 468, name: "SEB ENSKILDA INC", type: "NB", swift: "N" },
  { id: 469, name: "SG AMERICAS SECURITIES LLC", type: "NB", swift: "N" },
  { id: 470, name: "SHANGHAI CMRL BK LA BR", type: "BR", swift: "SCBKUS6LXXX" },
  { id: 471, name: "SHANGHAI CMRL BK LTD NY BR", type: "BR", swift: "SCBKUS33XXX" },
  { id: 472, name: "SHANGHAI CMRL BK LTD SF BR", type: "BR", swift: "SCBKUS6SXXX" },
  { id: 473, name: "SHINHAN BANK AMERICA", type: "SU", swift: "SHBKUS6LXXX" },
  { id: 474, name: "SHINHAN BK NY BR", type: "BR", swift: "SHBKUS6LNYX" },
  { id: 475, name: "SHIZUOKA BK LA BR", type: "BR", swift: "N" },
  { id: 476, name: "SHIZUOKA BK NY BR", type: "BR", swift: "N" },
  { id: 477, name: "SHOKO CHUKIN BK NY BR", type: "BR", swift: "N" },
  { id: 478, name: "SIB PORTFOLIO ADVISORS INC", type: "NB", swift: "N" },
  { id: 479, name: "SILICON VALLEY BANK", type: "HO", swift: "SVBKUS6S" },
  { id: 480, name: "SINOPAC BANCORP", type: "SU", swift: "FENBUS6L" },
  { id: 481, name: "SKANDINAVISKA ENSKILDA NY BR", type: "BR", swift: "ESSEUS33" },
  { id: 482, name: "SMBC SECURITIES INC", type: "NB", swift: "N" },
  { id: 483, name: "SOCIETE GENERALE CHICAGO BR", type: "BR", swift: "N" },
  { id: 484, name: "SOCIETE GENERALE DALLAS AGY", type: "BR", swift: "N" },
  { id: 485, name: "SOCIETE GENERALE NORTH AMERICA INC", type: "NB", swift: "N" },
  { id: 486, name: "SOCIETE GENERALE NY BR", type: "BR", swift: "N" },
  { id: 487, name: "SOUTH FINANCIAL GROUP INC THE", type: "HO", swift: "N" },
  { id: 488, name: "SOVEREIGN BANK", type: "SU", swift: "SVRNUS33XXX" },
  { id: 489, name: "STANCHART SECURITIES INTERNATIONAL INC", type: "NB", swift: "N" },
  { id: 490, name: "STANDARD CHARTERED BANK INTERNATIONAL (AMERICAS) LIMITED", type: "SU", swift: "N" },
  { id: 491, name: "STANDARD CHARTERED BK LA BR", type: "BR", swift: "SCBLUS66XXX" },
  { id: 492, name: "STANDARD CHARTERED BK NY BR", type: "BR", swift: "SCBLUS33XXX" },
  { id: 493, name: "STANDARD CHARTERED INTERNATIONAL (USA) LTD", type: "SU", swift: "N" },
  { id: 494, name: "STANDARD CHARTERED OVERSEAS INVESTMENT INC", type: "SU", swift: "N" },
  { id: 495, name: "STANDARD CHARTERED SECURITIES (NORTH AMERICA) INC", type: "NB", swift: "N" },
  { id: 496, name: "STATE BANK INDIA CHICAGO BR", type: "BR", swift: "N" },
  { id: 497, name: "STATE BANK OF INDIA (CALIFORNIA)", type: "SU", swift: "SBCAUS6LXXX" },
  { id: 498, name: "STATE BK OF INDIA LA AGY", type: "BR", swift: "N" },
  { id: 499, name: "STATE BK OF INDIA NY BR", type: "BR", swift: "N" },
  { id: 500, name: "STATE STREET BANK AND TRUST COMPANY", type: "HO", swift: "SBOSUS33" },
  { id: 501, name: "STATE STREET CORPORATION", type: "HO", swift: "N" },
  { id: 502, name: "STERLING BANCSHARES INC", type: "HO", swift: "N" },
  { id: 503, name: "STERLING BANK", type: "HO", swift: "STRLUS4HXXX" },
  { id: 504, name: "STRUCTURED OBLIGATIONS CORPORATION", type: "NB", swift: "N" },
  { id: 505, name: "STRUCTURED PRODUCTS CORP", type: "NB", swift: "N" },
  { id: 506, name: "SUMITOMO MITSUI BKG CORP LA BR", type: "BR", swift: "N" },
  { id: 507, name: "SUMITOMO MITSUI BKG CORP SF BR", type: "BR", swift: "N" },
  { id: 508, name: "SUMITOMO MITSUI BKG NY BR", type: "BR", swift: "SMBCUS33XXX" },
  { id: 509, name: "SUMITOMO TR BKG NY BR", type: "BR", swift: "STBCUS33XXX" },
  { id: 510, name: "SUMITOMO TRUST & BANKING CO (U.SA)", type: "SU", swift: "STUSUS33" },
  { id: 511, name: "SUNTRUST BANK", type: "HO", swift: "SNTRUS3ACOL" }, // Note: SWIFT might be specific to a location (COLumbus?), kept as listed.
  { id: 512, name: "SUNTRUST BANKS INC", type: "HO", swift: "N" },
  { id: 513, name: "SUNTRUST INVESTMENT SERVICES INC", type: "NB", swift: "N" },
  { id: 514, name: "SVB FINANCIAL GROUP", type: "HO", swift: "N" },
  { id: 515, name: "SVB SECURITIES", type: "NB", swift: "N" },
  { id: 516, name: "SVENSKA HANDELS AB PUBL NY BR", type: "BR", swift: "HANDUS33" },
  { id: 517, name: "SWEDBANK AB NY BR", type: "BR", swift: "SWEDUS33XXX" },
  { id: 518, name: "SWEDBANK FIRST SECURITIES LLC", type: "NB", swift: "N" },
  { id: 519, name: "SWISS AMERICAN SECURITIES INC", type: "NB", swift: "N" },
  { id: 520, name: "SYNOVUS FINANCIAL CORP", type: "HO", swift: "N" },
  { id: 521, name: "T C ZIRAAT BANKASI AS NY BR", type: "BR", swift: "TCZBUS33XXX" },
  { id: 522, name: "TAIPEI FUBON CMRL BK CO LA BR", type: "BR", swift: "TPBKUS6LXXX" },
  { id: 523, name: "TAIWAN BUS BK LA BR", type: "BR", swift: "MBBTUS6LXXX" },
  { id: 524, name: "TAIWAN CO-OP BK LA BR", type: "BR", swift: "FBOCUS6L" },
  { id: 525, name: "TAIWAN CO-OP BK SEATTLE BR", type: "BR", swift: "FBOCUS66" },
  { id: 526, name: "TAMARACK DISTRIBUTORS INC", type: "NB", swift: "N" },
  { id: 527, name: "TAUNUS CORPORATION", type: "SU", swift: "N" },
  { id: 528, name: "TD AMERITRADE CLEARING INC", type: "NB", swift: "N" },
  { id: 529, name: "TD AMERITRADE INC", type: "NB", swift: "N" },
  { id: 530, name: "TD BANK NA", type: "SU", swift: "CBNAUS33XXX" },
  { id: 531, name: "TD BANK US HOLDING COMPANY", type: "SU", swift: "N" },
  { id: 532, name: "TD BANK USA NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 533, name: "TD PROFESSIONAL EXECUTION INC", type: "NB", swift: "N" },
  { id: 534, name: "TD US P & C HOLDINGS ULC", type: "SU", swift: "N" },
  { id: 535, name: "TD WEALTH MANAGEMENT SERVICES INC", type: "NB", swift: "N" },
  { id: 536, name: "TEMPLETON/FRANKLIN INVESTMENT SERVICES INC", type: "NB", swift: "N" },
  { id: 537, name: "TEXAS CAPITAL BANCSHARES INC", type: "HO", swift: "N" },
  { id: 538, name: "TEXAS CAPITAL BANK NATIONAL ASSOCIATION", type: "HO", swift: "TXCBUS44" },
  { id: 539, name: "TORONTO-DOMINION BK HOU AGY", type: "BR", swift: "TDOMUS4HXXX" },
  { id: 540, name: "TORONTO-DOMINION BK NY BR", type: "BR", swift: "TDOMUS33XXX" },
  { id: 541, name: "TOTALBANK", type: "SU", swift: "TLBKUS3MXXX" },
  { id: 542, name: "TRANSATLANTIC BANK", type: "SU", swift: "N" },
  { id: 543, name: "TRANSATLANTIC HOLDING CORP", type: "SU", swift: "N" },
  { id: 544, name: "TRUSTMARK CORPORATION", type: "HO", swift: "N" },
  { id: 545, name: "TRUSTMARK NATIONAL BANK", type: "HO", swift: "TRNTUS41" },
  { id: 546, name: "TURKIYE VAKIFLAR BK NY BR", type: "BR", swift: "TVBAUS33XXX" },
  { id: 547, name: "U.S. BANCORP", type: "HO", swift: "N" },
  { id: 548, name: "U.S. BANK NATIONAL ASSOCIATION", type: "HO", swift: "USBKUS44" },
  { id: 549, name: "UBS 299 WEALTH MGMT NY BR", type: "BR", swift: "N" },
  { id: 550, name: "UBS AG AVE OF THE AMER BR", type: "BR", swift: "UBSWUS33PAK" },
  { id: 551, name: "UBS AG CHICAGO BR", type: "BR", swift: "UBSWUS33CHI" },
  { id: 552, name: "UBS AG LA BR", type: "BR", swift: "N" },
  { id: 553, name: "UBS AG MIAMI BR", type: "BR", swift: "UBSWUS33MIA" },
  { id: 554, name: "UBS AG NY BR", type: "BR", swift: "N" },
  { id: 555, name: "UBS AG PARK AVE BR", type: "BR", swift: "N" },
  { id: 556, name: "UBS AG SF BR", type: "BR", swift: "UBSWUS33SFO" },
  { id: 557, name: "UBS AG STAMFORD BR", type: "BR", swift: "UBSWUS33XXX" },
  { id: 558, name: "UBS AG TAMPA BR", type: "BR", swift: "N" },
  { id: 559, name: "UBS BANK USA", type: "SU", swift: "N" },
  { id: 560, name: "UBS CAPITAL INVESTORS INC", type: "NB", swift: "N" },
  { id: 561, name: "UBS CAPITAL MARKETS L.P.", type: "NB", swift: "N" },
  { id: 562, name: "UBS FINANCIAL SERVICES INC", type: "NB", swift: "WEBRUS33XXX" },
  { id: 563, name: "UBS INTERNATIONAL INC", type: "NB", swift: "N" },
  { id: 564, name: "UBS MANAGED FUND SERVICES INC", type: "NB", swift: "N" },
  { id: 565, name: "UBS PORTFOLIO LLC", type: "NB", swift: "N" },
  { id: 566, name: "UBS SECURITIES LLC", type: "NB", swift: "N" },
  { id: 567, name: "UBS WARBURG SWAPS INC", type: "NB", swift: "N" },
  { id: 568, name: "UNIBANCO SECURITIES INC", type: "NB", swift: "N" },
  { id: 569, name: "UNICREDIT CAPITAL MARKETS INC", type: "NB", swift: "N" },
  { id: 570, name: "UNICREDITO ITALIANO NY BR", type: "BR", swift: "UNCRUS33XXX" },
  { id: 571, name: "UNION BANK NATIONAL ASSOCIATION", type: "SU", swift: "BOFCUS33SFO" },
  { id: 572, name: "UNION PLANTERS HONG KONG INC", type: "SU", swift: "N" },
  { id: 573, name: "UNIONBANC INVESTMENT SERVICES LLC", type: "NB", swift: "N" },
  { id: 574, name: "UNIONBANCAL COMMERCIAL FUNDING CORPORATION", type: "NB", swift: "N" },
  { id: 575, name: "UNIONBANCAL CORPORATION", type: "SU", swift: "N" },
  { id: 576, name: "UNITED OVERSEAS BK LA AGY", type: "BR", swift: "UOVBUS6LXXX" },
  { id: 577, name: "UNITED OVERSEAS BK NY AGY", type: "BR", swift: "UOVBUS33XXX" },
  { id: 578, name: "UOB KAY HIAN (U.S) INC", type: "NB", swift: "N" },
  { id: 579, name: "UTRECHT-AMERICA HOLDINGS INC", type: "SU", swift: "N" },
  { id: 580, name: "VECTRA BANK COLORADO NATIONAL ASSOCIATION", type: "HO", swift: "N" },
  { id: 581, name: "VIB CORP", type: "SU", swift: "N" },
  { id: 582, name: "WACHOVIA BANK NATIONAL ASSOCIATION", type: "HO", swift: "PNBPUS33" },
  { id: 583, name: "WEBSTER BANK NATIONAL ASSOCIATION", type: "HO", swift: "N" },
  { id: 584, name: "WEBSTER FINANCIAL CORPORATION", type: "HO", swift: "N" },
  { id: 585, name: "WELLS FARGO & COMPANY", type: "HO", swift: "N" },
  { id: 586, name: "WELLS FARGO ADVISORS FINANCIAL NETWORK LLC", type: "NB", swift: "N" },
  { id: 587, name: "WELLS FARGO ADVISORS LLC", type: "NB", swift: "PNBPUS3WXXX" },
  { id: 588, name: "WELLS FARGO BANK NATIONAL ASSOCIATION", type: "HO", swift: "WFBIUS6S" },
  { id: 589, name: "WELLS FARGO BANK NORTHWEST NATIONAL ASSOCIATION", type: "HO", swift: "N" },
  { id: 590, name: "WELLS FARGO FUNDS DISTRIBUTOR LLC", type: "NB", swift: "N" },
  { id: 591, name: "WELLS FARGO HSBC TRADE BANK NATIONAL ASSOCIATION", type: "SU", swift: "N" },
  { id: 592, name: "WELLS FARGO INSTITUTIONAL SECURITIES LLC", type: "NB", swift: "N" },
  { id: 593, name: "WELLS FARGO INSURANCE SERVICES INVESTMENT ADVISORS INC", type: "NB", swift: "N" },
  { id: 594, name: "WELLS FARGO INVESTMENTS LLC", type: "NB", swift: "N" },
  { id: 595, name: "WELLS FARGO SECURITIES LLC", type: "NB", swift: "N" },
  { id: 596, name: "WESTLB AG NY BR", type: "BR", swift: "WELAUS3XXXX" },
  { id: 597, name: "WESTLB SECURITIES INC", type: "NB", swift: "N" },
  { id: 598, name: "WESTMINSTER RESEARCH ASSOCIATES LLC", type: "NB", swift: "N" },
  { id: 599, name: "WESTPAC BKG CORP NY BR", type: "BR", swift: "WPACUS33XXX" },
  { id: 600, name: "WHITNEY HOLDING CORPORATION", type: "HO", swift: "N" },
  { id: 601, name: "WHITNEY NATIONAL BANK", type: "HO", swift: "WHITUS44" },
  { id: 602, name: "WING LUNG BK LTD LA BR", type: "BR", swift: "WUBAUS66" },
  { id: 603, name: "WOORI AMERICA BANK", type: "SU", swift: "HVBKUS3NXXX" },
  { id: 604, name: "WOORI BK LA BR", type: "BR", swift: "N" },
  { id: 605, name: "WOORI INVESTMENT & SECURITIES AMERICA INC", type: "NB", swift: "N" },
  { id: 606, name: "ZIONS BANCORPORATION", type: "HO", swift: "N" },
  { id: 607, name: "ZIONS DIRECT INC", type: "NB", swift: "N" },
  { id: 608, name: "ZIONS FIRST NATIONAL BANK", type: "HO", swift: "N" }, // Assuming Type HO and SWIFT N as data was missing
];

// Function to search banks by name
export const searchBanks = (query: string): Bank[] => {
  if (!query || query.trim() === '') {
    // Return some major banks or first few alphabetically if no query
    const majorBankIds = [58, 336, 588, 165, 500]; // Example major IDs
    const majorBanks = bankData.filter(bank => majorBankIds.includes(bank.id));
    const otherBanks = bankData.filter(bank => !majorBankIds.includes(bank.id)).slice(0, 10 - majorBanks.length);
    return [...majorBanks, ...otherBanks];
  }

  const normalizedQuery = query.toLowerCase();

  // Prioritize matches starting with the query
  const startsWith = bankData.filter(bank =>
    bank.name.toLowerCase().startsWith(normalizedQuery)
  );

  // Then add matches containing the query (avoiding duplicates)
  const contains = bankData.filter(bank =>
    bank.name.toLowerCase().includes(normalizedQuery) &&
    !startsWith.some(swBank => swBank.id === bank.id) // Exclude those already found
  );

  // Combine and limit results
  return [...startsWith, ...contains].slice(0, 20);
};

// Function to get a bank by ID
export const getBankById = (id: number): Bank | undefined => {
  return bankData.find(bank => bank.id === id);
};

// Function to get all banks (paginated)
// Consider sorting alphabetically for better browsing if needed:
// const sortedBankData = [...bankData].sort((a, b) => a.name.localeCompare(b.name));
export const getAllBanks = (page: number = 1, pageSize: number = 20): Bank[] => {
  const start = (page - 1) * pageSize;
  const end = start + pageSize;
  // Use sortedBankData.slice(start, end) if you prefer alphabetical order
  return bankData.slice(start, end); // Currently returns in original (ID-based) order
};

// Export the banks data
export default bankData;